### ISSUE TITLE
Headless?

### ISSUE THREAD

**Issue by jmmease** [plotly/image-exporter#65] opened 2018-04-07 00:19 UTC
I built the project on OS X and ran the following png export command
```
~> bin/plotly-graph-exporter.js '{"data":[{"y": [3, 2, 5, 3]}],"layout":{}}' -o out.png
```
The `out.png` image is generated successfully, but I noticed that the electron window pops up in front of my other windows.

Is there any way to prevent the popup? I'm concerned this would be a bit disruptive for eventual python/R users.

cross reference: #21, plotly/plotly.py#880
cc: @cpsievert @etpinard @jackparmer

**Comment by jackparmer** [comment] 2018-04-08 01:28
@n-riesco @JamesCropcho @etpinard  Any thoughts here? Do we need https://github.com/plotly/image-exporter/pull/63 to prevent the popup?

**Comment by n-riesco** [comment] 2018-04-08 11:28
I guess that adding `show: false` [here](https://github.com/plotly/image-exporter/blob/a7e67453807aa08c3b27dbdfb0e81934eab5c134/src/app/runner/coerce-opts.js#L18) and [here](https://github.com/plotly/image-exporter/blob/a7e67453807aa08c3b27dbdfb0e81934eab5c134/src/app/server/coerce-opts.js#L26) could do the trick, but I haven't tested it.

**Comment by JamesCropcho** [comment] 2018-04-08 15:25
@jackparmer I don't believe I'll win any popularity contests with my thoughts here, but I'll share them as you have requested.

I do not believe that a window popping up for half a second (or even many such windows) in an application targeting computer-savvy types (e.g. Plotly users) is substantially "disruptive" to warrant significant effort from Plotly to remedy it.

**Comment by jackparmer** [comment] 2018-04-08 15:52
We've heard that pop-ups with [current offline PNG generation](
https://plot.ly/python/static-image-export/#export-static-image-offline)
cause issues when generating many images in series on a server without a
display. For example, we have customers who would like to generate
thousands of plot images as part of a nightly batch process.  So, yep, this
should be resolved.

**Comment by JamesCropcho** [comment] 2018-04-08 16:58
@jackparmer Ah, okay. That is a different use-case than @jmmease described.

I don't have any experience with this particular issue.
> I guess that adding show: false here and here could do the trick, but I haven't tested it.

@n-riesco's suggestion above sounds like as a good an initial experiment/step, as any. More broadly, an experimental approach is probably needed, i.e. trying various ideas which seem promising and seeing what works.

**Comment by JamesCropcho** [comment] 2018-04-08 16:59
>  Do we need #63 to prevent the popup?

@jackparmer As the author of #63, I am pretty sure that #63 would neither fix this, nor exacerbate it.

**Comment by etpinard** [comment] 2018-04-09 13:18
This issue is essentially a duplicate of https://github.com/plotly/image-exporter/issues/22

This repo won't attempt to do anything fancy (e.g. `xvfb`) to wrap electron in a headless executable. We'll just wait until electron supports chromium's `--headless` flag natively.

**Comment by etpinard** [comment] 2018-04-09 15:45
What does `show: false` do exactly? Does it still create a window and simply doesn't focus on it on creation?

**Comment by jackparmer** [comment] 2018-04-09 15:55
> Would this be a reasonable command line option eventually?

Definitely. The longterm vision was to to package this with plotly.py so we stop getting complaints like this: https://github.com/plotly/plotly.py/issues/880#issuecomment-377812417

**Comment by jmmease** [comment] 2018-04-09 16:05
Interesting, it seems that the `show: false` option suppresses the window for a png export
```
bin/plotly-graph-exporter.js '{"data":[{"y": [3, 2, 5, 3]}],"layout":{}}' -o out --format png
```
But when I do pdf export
```
bin/plotly-graph-exporter.js '{"data":[{"y": [3, 2, 5, 3]}],"layout":{}}' -o out --format pdf
```
There are actually two popup windows, and only the first one is hidden by the `show` option

**Comment by etpinard** [comment] 2018-04-09 16:15
what if you add `show: false` to this block:

https://github.com/plotly/image-exporter/blob/1c164bb2a4cb69f67a0f842aaf371bcb7721ca55/src/component/plotly-graph/render.js#L155-L158

**Comment by n-riesco** [comment] 2018-04-09 16:17
@etpinard The options are documented [here](https://electronjs.org/docs/api/browser-window#new-browserwindowoptions)

**Comment by jmmease** [comment] 2018-04-09 16:24
@etpinard Awesome, adding `show: false` to image-exporter/src/component/plotly-graph/render.js took care of the second window too.

**Comment by jackparmer** [comment] 2018-04-11 17:29
@JamesCropcho - Please go ahead and make a PR for this. Afterwards we can merge https://github.com/plotly/image-exporter/pull/63 and put out the first release! 🍾

**Comment by JamesCropcho** [comment] 2018-04-11 17:50
@jmmease Are you able to see https://github.com/plotly/image-exporter/pull/66? If so, is it identical to the changes you made, which worked as desired?

**Comment by etpinard** [comment] 2018-04-16 21:30
Closed via https://github.com/plotly/image-exporter/pull/72

**Closed by etpinard** 2018-04-16 21:30 UTC
